webtalk_init -webtalk_dir D:/Mtech/Vivado/Binary Weighted Shift Register/Binary Weighted Shift Register.sim/sim_1/synth/func/xsim/xsim.dir/Shift_Divider_TB_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Mar 29 18:38:27 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "213141686_0_0_564" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "585419d1-8a42-4d08-9017-7c06d2ee2d11" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e363f191c7e4466c8c769ccbe74c6211" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) Ultra 7 155H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2995 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "12" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "139 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "11 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "149" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "39" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "0.45_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "86596_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3433984734 -regid "213141686_0_0_564" -xml D:/Mtech/Vivado/Binary Weighted Shift Register/Binary Weighted Shift Register.sim/sim_1/synth/func/xsim/xsim.dir/Shift_Divider_TB_func_synth/webtalk/usage_statistics_ext_xsim.xml -html D:/Mtech/Vivado/Binary Weighted Shift Register/Binary Weighted Shift Register.sim/sim_1/synth/func/xsim/xsim.dir/Shift_Divider_TB_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm D:/Mtech/Vivado/Binary Weighted Shift Register/Binary Weighted Shift Register.sim/sim_1/synth/func/xsim/xsim.dir/Shift_Divider_TB_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
